QUERY_PARAMS = "queryParams"

PAGE_NUMBER = "pageNumber"
PAGE_SIZE = "pageSize"

DEFAULT_PAGE_SIZE = 10
DEFAULT_PAGE_NUMBER = 1

PAGINATION = "pagination"

NODE_ID = "nodeId"

ALMOST_ONCE = 0
ATLEAST_ONCE = 1
EXACTLY_ONCE = 2

SUCCESS = "success"
FAILED = "failed"

SOLUTION_STOPPED = "STOPPED"
SOLUTION_ADD_FAILED = "FAILED"
SOLUTION_RUNNING = "RUNNING"
SOLUTION_DEPLOYED = "DEPLOYED"

SOLUTION_ADD_TASK = "add"
SOLUTION_START_TASK = "start"
SOLUTION_STOP_TASK = "stop"
SOLUTION_STATUS_TASK = "status"
HEALTH_STATUS_TASK = "health_status"
